"""
DAF OS Quest90 — Asset Generator v1 サービス

Execution Planner（Quest88）とAsset Type Registry（Quest89）で「何を」「どう」
作るかは計画できるようになったが、実際の成果物（Digital Asset）はまだ何も
生成していなかった。このサービスはExecution Planを起点に、初めて実際の
デジタル資産（LINEスタンプ素材一式）を生成する。

v1では対象を line_sticker のみに限定する。

ゴール：
  Execution Plan → LINEスタンプ素材一式 → CEOレビュー待ち

v1の実装方針（あえてシンプルにする）：
- 画像生成APIはまだ使わない。Pillowで仮画像（プレースホルダー）を生成する。
  理由：(1) まずパイプライン完成を優先する (2) 画像生成API依存・コスト・
  失敗要因を避ける (3) LINEスタンプ制作工程の自動化そのものを検証するため。
  画像品質の改善はv2以降の課題（prompts.mdに将来の画像生成API用プロンプトを
  保存しておき、v2でそのまま利用できるようにしている）。

生成する成果物（outputs/generated_assets/line_sticker/）：
  metadata.md / phrases.md / prompts.md /
  stamp_01.png 〜 stamp_40.png（370×320px, 透明背景）/
  main.png（240×240px）/ tab.png（96×74px）/ stickers.zip

Quest91（Artifact Review Center）で、metadata.mdにGenerated By（制作担当AI社員）・
Reviewer・Reviewed At・Review Decision・Review Reason・Published Atの各項目を
追加した。これらはservices/artifact_review_service.pyがCEOレビューの結果を
書き戻すための項目で、生成直後はReviewer以降すべて「（未定）」になる。

必要な関数：
- generate_assets():                 Execution Plan（line_sticker）を起点に
                                      素材一式を生成し、結果を表すdictを返す
- generate_asset_generator_summary(): AI会議へ注入する短いMarkdown要約を返す

CLI:
  python services/asset_generator_service.py

重複生成防止：outputs/generated_assets/line_sticker/metadata.md が既に存在し、
Statusが pending_review または approved の場合は再生成しない。

Pillow未インストール・Execution Plan未生成・画像生成失敗のいずれでも例外を
投げず、DAF OS全体を止めない。
"""

import re
import sys
import zipfile
from datetime import datetime
from pathlib import Path

# `python services/asset_generator_service.py` のように直接実行された場合、
# リポジトリルートが sys.path に無く `services.*` を解決できないため追加する
# （services/execution_planner_service.py と同じ対策）。
_REPO_ROOT = str(Path(__file__).parent.parent)
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

_BASE_DIR = Path(__file__).parent.parent
_OUTPUTS_DIR = _BASE_DIR / "outputs"
_ASSET_TYPE = "line_sticker"
_GENERATED_ASSETS_DIR_NAME = "generated_assets"

_STAMP_COUNT = 40
_STAMP_SIZE = (370, 320)
_MAIN_SIZE = (240, 240)
_TAB_SIZE = (96, 74)

_DONE_STATUSES = frozenset({"pending_review", "approved"})

_NO_DATA_SUMMARY = "## Asset Generator Summary\n\n現在、生成されたAssetはありません。"

_UNSET = "（未定）"

# Asset Typeごとの制作担当AI社員（Quest91・v1固定）。
# docs/organization.md のDigital Asset Crewに対応する。
_GENERATED_BY = {
    "line_sticker": ["Lyra", "Vega", "Pulsar"],
}

# 日本語（かな漢字）を描画できるフォント候補。上から順に試し、
# 使えるものが無ければPillowのデフォルトフォントにフォールバックする。
_FONT_CANDIDATES = [
    "/System/Library/Fonts/AquaKana.ttc",
    "/System/Library/Fonts/Hiragino Sans GB.ttc",
    "/System/Library/Fonts/Supplemental/Arial Unicode.ttf",
]

# LINEスタンプ用の40フレーズ（v1固定・決定的）。
_PHRASES = [
    "おはよう", "ありがとう", "おつかれさま", "了解です", "こんにちは",
    "おやすみ", "がんばれ", "うれしい", "たのしい", "だいすき",
    "OK!", "またね", "元気だよ", "散歩いこう", "ごはんまだ？",
    "待ってるよ", "お腹すいた", "眠いよ", "嬉しいな", "ごめんね",
    "大丈夫？", "よろしくね", "すごいね", "さすが！", "わかった",
    "おめでとう", "気をつけてね", "応援してるよ", "楽しみ！", "いってきます",
    "ただいま", "おかえり", "頑張ろう", "無理しないで", "ゆっくりしてね",
    "また明日", "なるほど", "まかせて", "だいじょうぶ", "よし！",
]


def _output_dir(outputs_dir: Path) -> Path:
    return outputs_dir / _GENERATED_ASSETS_DIR_NAME / _ASSET_TYPE


def _extract_metadata_status(text: str) -> str | None:
    m = re.search(r"^Status:\s*\n(.+)$", text, re.MULTILINE)
    return m.group(1).strip() if m else None


def _load_font(size: int):
    from PIL import ImageFont
    for path in _FONT_CANDIDATES:
        try:
            if Path(path).exists():
                return ImageFont.truetype(path, size)
        except Exception:
            continue
    return ImageFont.load_default()


def _draw_character(draw, cx: float, cy: float, radius: float) -> None:
    """簡単なキャラクター風の丸アイコン（犬っぽい耳付き）を描画する。"""
    body_fill = (255, 224, 178, 255)
    outline = (120, 90, 60, 255)

    # 耳（先に描いて、頭で上から重ねる）
    ear_r = radius * 0.42
    draw.ellipse(
        [cx - radius - ear_r * 0.3, cy - radius - ear_r * 0.5,
         cx - radius + ear_r * 1.3, cy - radius + ear_r * 0.9],
        fill=body_fill, outline=outline, width=3,
    )
    draw.ellipse(
        [cx + radius - ear_r * 1.3, cy - radius - ear_r * 0.5,
         cx + radius + ear_r * 0.3, cy - radius + ear_r * 0.9],
        fill=body_fill, outline=outline, width=3,
    )

    # 頭（本体）
    draw.ellipse([cx - radius, cy - radius, cx + radius, cy + radius],
                 fill=body_fill, outline=outline, width=4)

    # 目
    eye_r = max(radius * 0.08, 4)
    eye_dx = radius * 0.42
    eye_dy = radius * 0.15
    draw.ellipse([cx - eye_dx - eye_r, cy - eye_dy - eye_r, cx - eye_dx + eye_r, cy - eye_dy + eye_r],
                 fill=(60, 40, 30, 255))
    draw.ellipse([cx + eye_dx - eye_r, cy - eye_dy - eye_r, cx + eye_dx + eye_r, cy - eye_dy + eye_r],
                 fill=(60, 40, 30, 255))

    # 鼻・口（簡単な弧）
    mouth_r = radius * 0.35
    draw.arc(
        [cx - mouth_r, cy + radius * 0.1, cx + mouth_r, cy + radius * 0.1 + mouth_r],
        start=20, end=160, fill=outline, width=max(int(radius * 0.05), 2),
    )


def _render_stamp(phrase: str) -> "Image.Image":
    from PIL import Image, ImageDraw

    img = Image.new("RGBA", _STAMP_SIZE, (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    w, h = _STAMP_SIZE
    cx, cy, r = w / 2, h * 0.42, min(w, h) * 0.32

    _draw_character(draw, cx, cy, r)

    font = _load_font(30)
    bbox = draw.textbbox((0, 0), phrase, font=font)
    tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
    tx = (w - tw) / 2 - bbox[0]
    ty = h - th - 28 - bbox[1]

    for dx, dy in ((-2, 0), (2, 0), (0, -2), (0, 2)):
        draw.text((tx + dx, ty + dy), phrase, font=font, fill=(255, 255, 255, 255))
    draw.text((tx, ty), phrase, font=font, fill=(50, 35, 25, 255))

    return img


def _render_icon(size: tuple[int, int]) -> "Image.Image":
    from PIL import Image, ImageDraw

    img = Image.new("RGBA", size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    w, h = size
    cx, cy = w / 2, h / 2
    r = min(w, h) * 0.38
    _draw_character(draw, cx, cy, r)
    return img


def _safe_line_sticker_plans(outputs_dir: Path) -> list[dict]:
    try:
        from services.execution_planner_service import list_execution_plans
        return list_execution_plans(asset_type=_ASSET_TYPE, outputs_dir=outputs_dir)
    except Exception as e:
        print(f"[警告] Execution Planの取得に失敗しました：{e}")
        return []


def generate_assets(outputs_dir: Path | None = None) -> dict:
    """
    outputs/execution_plans/ に line_sticker のExecution Planが存在する場合、
    outputs/generated_assets/line_sticker/ にLINEスタンプ素材一式
    （phrases.md / prompts.md / stamp_01.png〜stamp_40.png / main.png /
    tab.png / metadata.md / stickers.zip）を生成する。

    重複生成防止：既に metadata.md が存在し、Statusが pending_review または
    approved の場合は再生成しない。

    戻り値: {"status": "generated" | "skipped_existing" | "no_plan" | "error",
             "asset_type": "line_sticker", ...}
    Execution Planが無い・Pillow未インストール・画像生成失敗のいずれでも
    例外を投げず、DAF OS全体を止めない。
    """
    base_outputs_dir = outputs_dir or _OUTPUTS_DIR
    target_dir = _output_dir(base_outputs_dir)
    metadata_path = target_dir / "metadata.md"

    plans = _safe_line_sticker_plans(base_outputs_dir)
    if not plans:
        return {"status": "no_plan", "asset_type": _ASSET_TYPE}

    if metadata_path.exists():
        try:
            existing_status = _extract_metadata_status(metadata_path.read_text(encoding="utf-8"))
        except Exception:
            existing_status = None
        if existing_status in _DONE_STATUSES:
            return {
                "status": "skipped_existing",
                "asset_type": _ASSET_TYPE,
                "existing_status": existing_status,
                "output_dir": str(target_dir),
            }

    try:
        target_dir.mkdir(parents=True, exist_ok=True)

        project = plans[0].get("project") or "LINEスタンプ"
        generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")

        # phrases.md
        phrases_lines = [f"{i}. {p}" for i, p in enumerate(_PHRASES, start=1)]
        (target_dir / "phrases.md").write_text("\n".join(phrases_lines) + "\n", encoding="utf-8")

        # prompts.md（将来の画像生成API用）
        prompt_blocks = [
            f"stamp_{i:02d}:\n"
            f"A cute shiba inu LINE sticker saying \"{phrase}\", "
            "simple flat illustration, transparent background"
            for i, phrase in enumerate(_PHRASES, start=1)
        ]
        (target_dir / "prompts.md").write_text("\n\n".join(prompt_blocks) + "\n", encoding="utf-8")

        # スタンプ画像（仮画像・Pillow生成）
        stamp_filenames = []
        for i, phrase in enumerate(_PHRASES, start=1):
            filename = f"stamp_{i:02d}.png"
            img = _render_stamp(phrase)
            img.save(target_dir / filename)
            stamp_filenames.append(filename)

        # main.png / tab.png
        _render_icon(_MAIN_SIZE).save(target_dir / "main.png")
        _render_icon(_TAB_SIZE).save(target_dir / "tab.png")

        # metadata.md
        file_list = stamp_filenames + ["main.png", "tab.png", "stickers.zip"]
        generated_by = _GENERATED_BY.get(_ASSET_TYPE, [])
        metadata_lines = [
            "# LINE Sticker Metadata",
            "",
            "Project:",
            project,
            "",
            "Asset Type:",
            _ASSET_TYPE,
            "",
            "Generated At:",
            generated_at,
            "",
            "Status:",
            "pending_review",
            "",
            "Generated By:",
        ]
        metadata_lines.extend(f"- {name}" for name in generated_by)
        metadata_lines.extend([
            "",
            "Reviewer:",
            _UNSET,
            "",
            "Reviewed At:",
            _UNSET,
            "",
            "Review Decision:",
            _UNSET,
            "",
            "Review Reason:",
            _UNSET,
            "",
            "Published At:",
            _UNSET,
            "",
            "## Files",
        ])
        metadata_lines.extend(f"- {f}" for f in file_list)
        metadata_lines.extend([
            "",
            "## Notes",
            "v1では仮画像をPythonで生成。",
            "画像生成AI連携は今後のQuestで追加。",
        ])
        metadata_path.write_text("\n".join(metadata_lines) + "\n", encoding="utf-8")

        # stickers.zip（生成したPNGとmetadataをZIP化）
        zip_path = target_dir / "stickers.zip"
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            for filename in stamp_filenames + ["main.png", "tab.png"]:
                zf.write(target_dir / filename, arcname=filename)
            zf.write(metadata_path, arcname="metadata.md")

        # Notification Center（Quest92）へ通知する。失敗しても生成自体は成功として扱う。
        try:
            from services.notification_service import add_notification
            add_notification(
                "Asset Generated",
                "LINEスタンプ素材一式が生成されました。レビューしてください。",
                level="success",
                source="asset_generator",
                outputs_dir=base_outputs_dir,
            )
        except Exception as e:
            print(f"[警告] Notification Centerへの通知に失敗しました：{e}")

        return {
            "status": "generated",
            "asset_type": _ASSET_TYPE,
            "project": project,
            "output_dir": str(target_dir),
            "zip_path": str(zip_path),
            "stamp_count": len(stamp_filenames),
        }
    except Exception as e:
        print(f"[警告] Asset Generatorの生成に失敗しました：{e}")
        return {"status": "error", "asset_type": _ASSET_TYPE, "error": str(e)}


def generate_asset_generator_summary(outputs_dir: Path | None = None) -> str:
    """
    outputs/generated_assets/line_sticker/metadata.md を読み込み、AI会議へ
    注入する短いMarkdown要約に整形する（services/memory_service.py の
    load_company_memory() から呼ばれる）。ファイル未存在・読み込み失敗の
    いずれの場合も「現在、生成されたAssetはありません。」を返す。例外を投げない。
    """
    try:
        base = outputs_dir or _OUTPUTS_DIR
        metadata_path = _output_dir(base) / "metadata.md"
        if not metadata_path.exists():
            return _NO_DATA_SUMMARY

        text = metadata_path.read_text(encoding="utf-8")
        status = _extract_metadata_status(text) or "unknown"

        lines = [
            "## Asset Generator Summary",
            "",
            "### Generated Assets",
            "",
            f"- {_ASSET_TYPE}: {status}",
            "",
            "### Output",
            f"outputs/{_GENERATED_ASSETS_DIR_NAME}/{_ASSET_TYPE}/stickers.zip",
            "",
            "### Recommendation",
            "CEOが生成物を確認してください。",
        ]
        return "\n".join(lines).rstrip()
    except Exception as e:
        print(f"[警告] Asset Generator Summaryの生成に失敗しました：{e}")
        return _NO_DATA_SUMMARY


def list_generated_assets(outputs_dir: Path | None = None) -> list[dict]:
    """
    outputs/generated_assets/*/metadata.md を読み込み専用でスキャンし、
    Dashboard（Quest93試験運用版）の「Generated Assets」タブ向けに構造化
    データで返す（Dashboard/CEO Home APIから呼ばれる）。

    戻り値: [{"asset_type": str, "status": str, "files_count": int,
              "generated_at": str | None, "zip_path": str | None}, ...]
    ディレクトリ未存在・読み込み失敗のいずれでも例外を投げず、空リストを返す。
    """
    try:
        base = outputs_dir or _OUTPUTS_DIR
        assets_root = base / _GENERATED_ASSETS_DIR_NAME
        if not assets_root.exists():
            return []

        results = []
        for asset_dir in sorted(assets_root.iterdir()):
            metadata_path = asset_dir / "metadata.md"
            if not asset_dir.is_dir() or not metadata_path.exists():
                continue
            try:
                text = metadata_path.read_text(encoding="utf-8")
            except Exception:
                continue

            generated_at_m = re.search(r"^Generated At:\s*\n(.+)$", text, re.MULTILINE)
            zip_path = asset_dir / "stickers.zip"

            results.append({
                "asset_type": asset_dir.name,
                "status": _extract_metadata_status(text) or "unknown",
                "files_count": len([f for f in asset_dir.iterdir() if f.is_file()]),
                "generated_at": generated_at_m.group(1).strip() if generated_at_m else None,
                "zip_path": f"outputs/{_GENERATED_ASSETS_DIR_NAME}/{asset_dir.name}/stickers.zip" if zip_path.exists() else None,
            })
        return results
    except Exception as e:
        print(f"[警告] Generated Assetsの取得に失敗しました：{e}")
        return []


if __name__ == "__main__":
    # Quest90: Dashboard/main.pyの日次バッチを待たずに手動で再生成したい場合のCLI導線。
    #   python services/asset_generator_service.py
    result = generate_assets()
    print(f"[Asset Generator] {result}")
    print()
    print(generate_asset_generator_summary())
