"""
DAF OS Quest90 — Asset Generator v1 サービス（Quest98でRenderer分離）

Execution Planner（Quest88）とAsset Type Registry（Quest89）で「何を」「どう」
作るかは計画できるようになったが、実際の成果物（Digital Asset）はまだ何も
生成していなかった。このサービスはExecution Planを起点に、初めて実際の
デジタル資産（LINEスタンプ素材一式）を生成する。

v1では対象を line_sticker のみに限定する。

ゴール：
  Execution Plan → LINEスタンプ素材一式 → CEOレビュー待ち

Quest98：責務分離（Image Generation Pipeline準備）
- Quest90〜97まで、このファイルが直接Pillowで描画していたが、将来
  画像生成AI（OpenAI・Google・FLUX・Stability AI等）へ切り替えられる
  よう、実際の描画処理を services/image_generation_service.py
  （Rendererの切替入口）→ services/renderers/pillow_renderer.py
  （実際の描画実装）へ移した。このファイルは「どのRendererを使うか」を
  知らない。
- プロンプト文字列（prompts.md）の組み立ても services/prompt_builder_service.py
  （Character Bible → Style Guide → Image Prompt）に委譲した。
- Quest98では画像生成APIはまだ導入しない。Pillow Rendererのみで、
  描画結果はQuest95までと完全に同じ（見た目は変えていない）。

生成する成果物（outputs/generated_assets/line_sticker/<project_id>/。
Quest97でProject別に分離。project_id=="legacy"はQuest90〜96時代の
フラット形式・出力先そのまま）：
  metadata.md / phrases.md / prompts.md /
  stamp_01.png 〜 stamp_40.png（370×320px, 透明背景）/
  main.png（240×240px）/ tab.png（96×74px）/ stickers.zip

Quest91（Artifact Review Center）で、metadata.mdにGenerated By（制作担当AI社員）・
Reviewer・Reviewed At・Review Decision・Review Reason・Published Atの各項目を
追加した。これらはservices/artifact_review_service.pyがCEOレビューの結果を
書き戻すための項目で、生成直後はReviewer以降すべて「（未定）」になる。

必要な関数：
- generate_assets():                 Execution Plan（line_sticker）を起点に
                                      素材一式を生成し、結果を表すdictを返す
- generate_asset_generator_summary(): AI会議へ注入する短いMarkdown要約を返す

CLI:
  python services/asset_generator_service.py

重複生成防止：Project単位（outputs/generated_assets/line_sticker/<project_id>/
metadata.md）で既にStatusが pending_review または approved の場合、その
Projectは再生成しない。別Projectであれば新しく生成できる（Quest97）。

Renderer未インストール（Pillow未インストール等）・Execution Plan未生成・
画像生成失敗のいずれでも例外を投げず、DAF OS全体を止めない。
"""

import re
import sys
import zipfile
from datetime import datetime
from pathlib import Path

# `python services/asset_generator_service.py` のように直接実行された場合、
# リポジトリルートが sys.path に無く `services.*` を解決できないため追加する
# （services/execution_planner_service.py と同じ対策）。
_REPO_ROOT = str(Path(__file__).parent.parent)
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

_BASE_DIR = Path(__file__).parent.parent
_OUTPUTS_DIR = _BASE_DIR / "outputs"
_ASSET_TYPE = "line_sticker"
_GENERATED_ASSETS_DIR_NAME = "generated_assets"

_STAMP_COUNT = 40
_MAIN_SIZE = (240, 240)
_TAB_SIZE = (96, 74)

_DONE_STATUSES = frozenset({"pending_review", "approved"})

_NO_DATA_SUMMARY = "## Asset Generator Summary\n\n現在、生成されたAssetはありません。"

_UNSET = "（未定）"

# Asset Typeごとの制作担当AI社員（Quest91・v1固定）。
# docs/organization.md のDigital Asset Crewに対応する。
_GENERATED_BY = {
    "line_sticker": ["Lyra", "Vega", "Pulsar"],
}

# LINEスタンプ用の40フレーズ（v1固定・決定的）。
_PHRASES = [
    "おはよう", "ありがとう", "おつかれさま", "了解です", "こんにちは",
    "おやすみ", "がんばれ", "うれしい", "たのしい", "だいすき",
    "OK!", "またね", "元気だよ", "散歩いこう", "ごはんまだ？",
    "待ってるよ", "お腹すいた", "眠いよ", "嬉しいな", "ごめんね",
    "大丈夫？", "よろしくね", "すごいね", "さすが！", "わかった",
    "おめでとう", "気をつけてね", "応援してるよ", "楽しみ！", "いってきます",
    "ただいま", "おかえり", "頑張ろう", "無理しないで", "ゆっくりしてね",
    "また明日", "なるほど", "まかせて", "だいじょうぶ", "よし！",
]


def _output_dir(outputs_dir: Path) -> Path:
    return outputs_dir / _GENERATED_ASSETS_DIR_NAME / _ASSET_TYPE


_LEGACY_PROJECT_ID = "legacy"


def _slug_for_project(name: str) -> str:
    """
    Quest97：Project名から安全なフォルダ名（slug）を作る。
    英数字トークン（あれば）を可読プレフィックスとして残しつつ、名前全体の
    ハッシュを必ず付与する。日本語のProject名は「LINEスタンプ」のように
    共通の英単語を含むことが多く、英数字トークンだけをslugにすると
    別のProject同士が同じフォルダに衝突してしまうため（例："猫のLINEスタンプ"
    と"犬のLINEスタンプ"が両方"line"になる）、ハッシュで一意性を担保する。
    同じ名前なら常に同じslugになる（決定的）。
    """
    import hashlib
    digest = hashlib.md5((name or "").encode("utf-8")).hexdigest()[:10]
    tokens = re.findall(r"[A-Za-z0-9]+", name or "")
    if tokens:
        prefix = "_".join(t.lower() for t in tokens)[:40]
        if prefix:
            return f"{prefix}_{digest}"
    return f"project_{digest}"


def _project_output_dir(outputs_dir: Path, project_id: str) -> Path:
    """
    Quest97：Project別の出力先を返す。project_id=="legacy"の場合は
    outputs/generated_assets/line_sticker/ 直下（Quest90〜96の旧形式）を、
    それ以外は outputs/generated_assets/line_sticker/<project_id>/ を返す。
    """
    base = _output_dir(outputs_dir)
    if project_id == _LEGACY_PROJECT_ID:
        return base
    return base / project_id


def _extract_metadata_status(text: str) -> str | None:
    m = re.search(r"^Status:\s*\n(.+)$", text, re.MULTILINE)
    return m.group(1).strip() if m else None



def _safe_line_sticker_plans(outputs_dir: Path) -> list[dict]:
    try:
        from services.execution_planner_service import list_execution_plans
        return list_execution_plans(asset_type=_ASSET_TYPE, outputs_dir=outputs_dir)
    except Exception as e:
        print(f"[警告] Execution Planの取得に失敗しました：{e}")
        return []


def generate_assets(outputs_dir: Path | None = None, project_name: str | None = None) -> dict:
    """
    Quest97：outputs/execution_plans/ に登録されたline_stickerのExecution
    Planを起点に、Project別（outputs/generated_assets/line_sticker/<slug>/）
    にLINEスタンプ素材一式を生成する。

    project_nameを指定した場合：そのProjectのExecution Planのみを対象に
    1件だけ生成する（services/project_service.generate_project_assets()から
    呼ばれる通常経路）。該当するExecution Planが無ければ"no_plan"を返す。

    project_nameを指定しない場合（例：CLI `python services/asset_generator_service.py`
    の直接実行）：登録されている全line_sticker Execution Planを対象に、
    Project単位でバッチ生成する。戻り値の"results"に各Projectの結果を含め、
    1件でも新規生成があれば全体のstatusを"generated"とする。

    重複生成防止：Project単位でmetadata.mdが既に存在し、Statusが
    pending_review または approved の場合はそのProjectの再生成をスキップする
    （別Projectであれば新しく生成できる）。

    戻り値（project_name指定時）:
      {"status": "generated" | "skipped_existing" | "no_plan" | "error",
       "asset_type": "line_sticker", "project": str, "project_id": str, ...}
    戻り値（project_name未指定・バッチ時）:
      {"status": "generated" | "skipped_existing" | "no_plan" | "error",
       "asset_type": "line_sticker", "results": [...]}

    Execution Planが無い・Pillow未インストール・画像生成失敗のいずれでも
    例外を投げず、DAF OS全体を止めない。
    """
    base_outputs_dir = outputs_dir or _OUTPUTS_DIR
    plans = _safe_line_sticker_plans(base_outputs_dir)
    if not plans:
        return {"status": "no_plan", "asset_type": _ASSET_TYPE}

    if project_name is not None:
        matching = [p for p in plans if p.get("project") == project_name]
        if not matching:
            return {"status": "no_plan", "asset_type": _ASSET_TYPE, "project": project_name}
        return _generate_assets_for_project(matching[0].get("project") or project_name, base_outputs_dir)

    # project_name未指定：登録済みの全line_sticker Planを対象にバッチ生成する
    results = [
        _generate_assets_for_project(p.get("project") or "LINEスタンプ", base_outputs_dir)
        for p in plans
    ]
    if any(r.get("status") == "generated" for r in results):
        overall_status = "generated"
    elif any(r.get("status") == "error" for r in results):
        overall_status = "error"
    elif results:
        overall_status = "skipped_existing"
    else:
        overall_status = "no_plan"
    return {"status": overall_status, "asset_type": _ASSET_TYPE, "results": results}


def _legacy_done_result(project_name: str, base_outputs_dir: Path) -> dict | None:
    """
    Quest97：Project名が旧形式（フラット・legacy）のmetadata.mdの"Project:"と
    一致し、かつStatusがpending_review/approved済みの場合、そのdictを返す。
    一致しない・未生成・読み込み失敗の場合はNoneを返す。

    新形式のフォルダにはまだ何も無くても、同じProjectが既にlegacyとして
    生成済みなら二重生成しないようにするための重複防止チェック
    （generate_assets()導入前のQuest90〜96時代からある単一データを
    誤って作り直さないため）。
    """
    legacy_dir = _output_dir(base_outputs_dir)
    legacy_metadata = legacy_dir / "metadata.md"
    if not legacy_metadata.exists():
        return None
    try:
        text = legacy_metadata.read_text(encoding="utf-8")
    except Exception:
        return None
    project_m = re.search(r"^Project:\s*\n(.+)$", text, re.MULTILINE)
    legacy_project = project_m.group(1).strip() if project_m else None
    if legacy_project != project_name:
        return None
    status = _extract_metadata_status(text)
    if status not in _DONE_STATUSES:
        return None
    return {
        "status": "skipped_existing",
        "asset_type": _ASSET_TYPE,
        "project": project_name,
        "project_id": _LEGACY_PROJECT_ID,
        "existing_status": status,
        "output_dir": str(legacy_dir),
    }


def _generate_assets_for_project(project_name: str, base_outputs_dir: Path) -> dict:
    """
    Quest97：1つのProject（project_name）について、Project別フォルダへ
    LINEスタンプ素材一式（phrases.md / prompts.md / stamp_01.png〜stamp_40.png /
    main.png / tab.png / metadata.md / stickers.zip）を生成する。
    generate_assets()から呼ばれる内部ヘルパー。
    """
    project_id = _slug_for_project(project_name)
    target_dir = _project_output_dir(base_outputs_dir, project_id)
    metadata_path = target_dir / "metadata.md"

    if metadata_path.exists():
        try:
            existing_status = _extract_metadata_status(metadata_path.read_text(encoding="utf-8"))
        except Exception:
            existing_status = None
        if existing_status in _DONE_STATUSES:
            return {
                "status": "skipped_existing",
                "asset_type": _ASSET_TYPE,
                "project": project_name,
                "project_id": project_id,
                "existing_status": existing_status,
                "output_dir": str(target_dir),
            }

    legacy_result = _legacy_done_result(project_name, base_outputs_dir)
    if legacy_result:
        return legacy_result

    try:
        target_dir.mkdir(parents=True, exist_ok=True)

        project = project_name
        generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")

        # Quest98：Character Bibleを読み込み、Prompt Builder経由でprompts.mdを
        # 組み立てる（Asset Generatorはプロンプトの中身を組み立てない）。
        from services.prompt_builder_service import load_character_bible, build_prompts_for_phrases
        from services.image_generation_service import (
            render_stamp_image, render_icon_image, get_renderer_info,
        )

        character_bible = load_character_bible()
        renderer_info = get_renderer_info()

        # phrases.md
        phrases_lines = [f"{i}. {p}" for i, p in enumerate(_PHRASES, start=1)]
        (target_dir / "phrases.md").write_text("\n".join(phrases_lines) + "\n", encoding="utf-8")

        # prompts.md（将来の画像生成API用。Quest98からPrompt Builder経由で組み立てる）
        prompts = build_prompts_for_phrases(_PHRASES, character_bible=character_bible)
        prompt_blocks = [
            f"stamp_{i:02d}:\n{prompt}"
            for i, prompt in enumerate(prompts, start=1)
        ]
        (target_dir / "prompts.md").write_text("\n\n".join(prompt_blocks) + "\n", encoding="utf-8")

        # スタンプ画像（Quest98：Image Generation Service経由でRenderer
        # （既定はPillow）へ委譲する。Asset Generatorはどの絵作りをしているか知らない）
        stamp_filenames = []
        for i, phrase in enumerate(_PHRASES, start=1):
            filename = f"stamp_{i:02d}.png"
            img = render_stamp_image(phrase, i - 1, character_bible=character_bible)
            img.save(target_dir / filename)
            stamp_filenames.append(filename)

        # main.png / tab.png
        render_icon_image(_MAIN_SIZE, character_bible=character_bible).save(target_dir / "main.png")
        render_icon_image(_TAB_SIZE, character_bible=character_bible).save(target_dir / "tab.png")

        # metadata.md
        file_list = stamp_filenames + ["main.png", "tab.png", "stickers.zip"]
        generated_by = _GENERATED_BY.get(_ASSET_TYPE, [])
        metadata_lines = [
            "# LINE Sticker Metadata",
            "",
            "Project:",
            project,
            "",
            "Asset Type:",
            _ASSET_TYPE,
            "",
            "Renderer:",
            renderer_info.get("display_name", "unknown"),
            "",
            "Generated At:",
            generated_at,
            "",
            "Status:",
            "pending_review",
            "",
            "Generated By:",
        ]
        metadata_lines.extend(f"- {name}" for name in generated_by)
        metadata_lines.extend([
            "",
            "Reviewer:",
            _UNSET,
            "",
            "Reviewed At:",
            _UNSET,
            "",
            "Review Decision:",
            _UNSET,
            "",
            "Review Reason:",
            _UNSET,
            "",
            "Published At:",
            _UNSET,
            "",
            "## Files",
        ])
        metadata_lines.extend(f"- {f}" for f in file_list)
        metadata_lines.extend([
            "",
            "## Notes",
            "v1では仮画像をPythonで生成。",
            "画像生成AI連携は今後のQuestで追加。",
        ])
        metadata_path.write_text("\n".join(metadata_lines) + "\n", encoding="utf-8")

        # stickers.zip（生成したPNGとmetadataをZIP化）
        zip_path = target_dir / "stickers.zip"
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            for filename in stamp_filenames + ["main.png", "tab.png"]:
                zf.write(target_dir / filename, arcname=filename)
            zf.write(metadata_path, arcname="metadata.md")

        # Notification Center（Quest92）へ通知する。失敗しても生成自体は成功として扱う。
        # Quest97：Project名をメッセージに含めることで、複数Projectを続けて
        # 生成した場合でも(title, source, message)の重複防止に巻き込まれず、
        # それぞれの通知が記録されるようにする。
        try:
            from services.notification_service import add_notification
            add_notification(
                "Asset Generated",
                f"{project} のLINEスタンプ素材一式が生成されました。レビューしてください。",
                level="success",
                source="asset_generator",
                outputs_dir=base_outputs_dir,
            )
        except Exception as e:
            print(f"[警告] Notification Centerへの通知に失敗しました：{e}")

        return {
            "status": "generated",
            "asset_type": _ASSET_TYPE,
            "project": project,
            "project_id": project_id,
            "output_dir": str(target_dir),
            "zip_path": str(zip_path),
            "stamp_count": len(stamp_filenames),
        }
    except Exception as e:
        print(f"[警告] Asset Generatorの生成に失敗しました（{project_name}）：{e}")
        return {"status": "error", "asset_type": _ASSET_TYPE, "project": project_name, "project_id": project_id, "error": str(e)}


def generate_asset_generator_summary(outputs_dir: Path | None = None) -> str:
    """
    outputs/generated_assets/line_sticker/ 配下のProject別成果物（＋legacy）を
    読み込み、AI会議へ注入する短いMarkdown要約に整形する
    （services/memory_service.py の load_company_memory() から呼ばれる）。
    Quest97：複数Projectがある場合は最新（generated_at降順の先頭）1件の
    Statusを代表として示し、件数も併記する。1件も無い場合は
    「現在、生成されたAssetはありません。」を返す。例外を投げない。
    """
    try:
        base = outputs_dir or _OUTPUTS_DIR
        projects = list_line_sticker_projects(outputs_dir=base)
        if not projects:
            return _NO_DATA_SUMMARY

        latest = projects[0]
        pid = latest["project_id"]
        zip_rel = (
            f"outputs/{_GENERATED_ASSETS_DIR_NAME}/{_ASSET_TYPE}/stickers.zip"
            if pid == _LEGACY_PROJECT_ID
            else f"outputs/{_GENERATED_ASSETS_DIR_NAME}/{_ASSET_TYPE}/{pid}/stickers.zip"
        )

        lines = [
            "## Asset Generator Summary",
            "",
            "### Generated Assets",
            "",
            f"- {_ASSET_TYPE}: {len(projects)}件のProject（最新: {latest['project_name']} / {latest['status']}）",
            "",
            "### Output",
            zip_rel,
            "",
            "### Recommendation",
            "CEOが生成物を確認してください。",
        ]
        return "\n".join(lines).rstrip()
    except Exception as e:
        print(f"[警告] Asset Generator Summaryの生成に失敗しました：{e}")
        return _NO_DATA_SUMMARY


def _line_sticker_project_entry(dir_path: Path, metadata_path: Path, project_id: str) -> dict | None:
    """
    Quest97：1つのLINE Sticker Project（またはlegacyのフラット出力）の
    metadata.mdからDashboard一覧向けのサマリを作る。読み込み失敗時はNoneを返す。
    """
    try:
        text = metadata_path.read_text(encoding="utf-8")
    except Exception:
        return None

    project_m = re.search(r"^Project:\s*\n(.+)$", text, re.MULTILINE)
    generated_at_m = re.search(r"^Generated At:\s*\n(.+)$", text, re.MULTILINE)
    stamp_files = sorted(f.name for f in dir_path.glob("stamp_*.png") if f.is_file())
    zip_path = dir_path / "stickers.zip"

    default_name = "（レガシー・旧形式）" if project_id == _LEGACY_PROJECT_ID else project_id
    return {
        "project_id": project_id,
        "project_name": project_m.group(1).strip() if project_m else default_name,
        "status": _extract_metadata_status(text) or "unknown",
        "generated_at": generated_at_m.group(1).strip() if generated_at_m else None,
        "files_count": len([f for f in dir_path.iterdir() if f.is_file()]),
        "stamp_count": len(stamp_files),
        "thumbnail": stamp_files[0] if stamp_files else None,
        "zip_exists": zip_path.exists(),
    }


def list_line_sticker_projects(outputs_dir: Path | None = None) -> list[dict]:
    """
    Quest97：outputs/generated_assets/line_sticker/ 配下のProject別成果物
    （新形式のサブフォルダ）と、Quest90〜96時代のフラット形式（legacy）を
    まとめて一覧で返す（Dashboardの「LINEスタンプ Project別成果物」向け）。

    戻り値: [{"project_id": str, "project_name": str, "status": str,
              "generated_at": str | None, "files_count": int,
              "stamp_count": int, "thumbnail": str | None,
              "zip_exists": bool}, ...]
    generated_atの新しい順（無ければ末尾）に並べる。ディレクトリ未存在・
    読み込み失敗のいずれでも例外を投げず、空リストを返す。
    """
    try:
        base = outputs_dir or _OUTPUTS_DIR
        line_sticker_dir = _output_dir(base)
        if not line_sticker_dir.exists():
            return []

        results = []

        legacy_metadata = line_sticker_dir / "metadata.md"
        if legacy_metadata.exists():
            entry = _line_sticker_project_entry(line_sticker_dir, legacy_metadata, _LEGACY_PROJECT_ID)
            if entry:
                results.append(entry)

        for sub in sorted(line_sticker_dir.iterdir()):
            if not sub.is_dir():
                continue
            metadata_path = sub / "metadata.md"
            if not metadata_path.exists():
                continue
            entry = _line_sticker_project_entry(sub, metadata_path, sub.name)
            if entry:
                results.append(entry)

        results.sort(key=lambda e: e.get("generated_at") or "", reverse=True)
        return results
    except Exception as e:
        print(f"[警告] LINE Sticker Project一覧の取得に失敗しました：{e}")
        return []


def list_generated_assets(outputs_dir: Path | None = None) -> list[dict]:
    """
    outputs/generated_assets/*/metadata.md を読み込み専用でスキャンし、
    Dashboard（Quest93試験運用版）の「Generated Assets」タブ向けに構造化
    データで返す（Dashboard/CEO Home APIから呼ばれる）。

    Quest97：line_sticker はProject別サブフォルダ（＋後方互換のlegacyフラット
    形式）を持つため、他のAsset Type（フラット構造のまま）とは別に
    list_line_sticker_projects()を使って1行1Projectで展開する。

    戻り値: [{"asset_type": str, "status": str, "files_count": int,
              "generated_at": str | None, "zip_path": str | None,
              "project_id": str | None}, ...]
    ディレクトリ未存在・読み込み失敗のいずれでも例外を投げず、空リストを返す。
    """
    try:
        base = outputs_dir or _OUTPUTS_DIR
        assets_root = base / _GENERATED_ASSETS_DIR_NAME
        if not assets_root.exists():
            return []

        results = []
        for asset_dir in sorted(assets_root.iterdir()):
            if not asset_dir.is_dir():
                continue

            if asset_dir.name == _ASSET_TYPE:
                for project in list_line_sticker_projects(outputs_dir=base):
                    pid = project["project_id"]
                    sub_dir = _project_output_dir(base, pid)
                    zip_path = sub_dir / "stickers.zip"
                    results.append({
                        "asset_type": _ASSET_TYPE,
                        "project_id": pid,
                        "status": project["status"],
                        "files_count": project["files_count"],
                        "generated_at": project["generated_at"],
                        "zip_path": (
                            f"outputs/{_GENERATED_ASSETS_DIR_NAME}/{_ASSET_TYPE}/stickers.zip"
                            if pid == _LEGACY_PROJECT_ID and zip_path.exists()
                            else f"outputs/{_GENERATED_ASSETS_DIR_NAME}/{_ASSET_TYPE}/{pid}/stickers.zip"
                            if zip_path.exists() else None
                        ),
                    })
                continue

            metadata_path = asset_dir / "metadata.md"
            if not metadata_path.exists():
                continue
            try:
                text = metadata_path.read_text(encoding="utf-8")
            except Exception:
                continue

            generated_at_m = re.search(r"^Generated At:\s*\n(.+)$", text, re.MULTILINE)
            zip_path = asset_dir / "stickers.zip"

            results.append({
                "asset_type": asset_dir.name,
                "project_id": None,
                "status": _extract_metadata_status(text) or "unknown",
                "files_count": len([f for f in asset_dir.iterdir() if f.is_file()]),
                "generated_at": generated_at_m.group(1).strip() if generated_at_m else None,
                "zip_path": f"outputs/{_GENERATED_ASSETS_DIR_NAME}/{asset_dir.name}/stickers.zip" if zip_path.exists() else None,
            })
        return results
    except Exception as e:
        print(f"[警告] Generated Assetsの取得に失敗しました：{e}")
        return []


def get_line_sticker_detail(outputs_dir: Path | None = None, project_id: str | None = None) -> dict:
    """
    Quest94 v2で追加、Quest97でProject別対応。Dashboardの
    「LINEスタンプ生成結果」詳細向けに、指定Project
    （project_id未指定または"legacy"の場合はQuest90〜96時代のフラット形式）
    の内容を構造化データで返す（フォルダを開かなくてもmetadata・phrases・
    スタンプ一覧・zip有無を確認できるようにするため）。

    戻り値: {"exists": bool, "project_id": str, "project_name": str | None,
             "output_dir": str, "status": str, "metadata_text": str,
             "phrases_text": str, "stamp_files": list[str],
             "main_exists": bool, "tab_exists": bool, "zip_exists": bool}
    未生成・読み込み失敗のいずれでも例外を投げず、{"exists": False}を返す。
    """
    pid = project_id or _LEGACY_PROJECT_ID
    try:
        base = outputs_dir or _OUTPUTS_DIR
        target_dir = _project_output_dir(base, pid)
        metadata_path = target_dir / "metadata.md"
        if not target_dir.exists() or not metadata_path.exists():
            return {"exists": False, "project_id": pid}

        try:
            metadata_text = metadata_path.read_text(encoding="utf-8")
        except Exception:
            metadata_text = ""

        phrases_text = ""
        phrases_path = target_dir / "phrases.md"
        if phrases_path.exists():
            try:
                phrases_text = phrases_path.read_text(encoding="utf-8")
            except Exception:
                phrases_text = ""

        stamp_files = sorted(f.name for f in target_dir.glob("stamp_*.png") if f.is_file())
        project_m = re.search(r"^Project:\s*\n(.+)$", metadata_text, re.MULTILINE)

        return {
            "exists": True,
            "project_id": pid,
            "project_name": project_m.group(1).strip() if project_m else None,
            "output_dir": str(target_dir),
            "status": _extract_metadata_status(metadata_text) or "unknown",
            "metadata_text": metadata_text,
            "phrases_text": phrases_text,
            "stamp_files": stamp_files,
            "main_exists": (target_dir / "main.png").exists(),
            "tab_exists": (target_dir / "tab.png").exists(),
            "zip_exists": (target_dir / "stickers.zip").exists(),
        }
    except Exception as e:
        print(f"[警告] LINE Sticker詳細の取得に失敗しました：{e}")
        return {"exists": False, "project_id": pid, "error": str(e)}


if __name__ == "__main__":
    # Quest90: Dashboard/main.pyの日次バッチを待たずに手動で再生成したい場合のCLI導線。
    # Quest97: project_name未指定のため、登録済みの全line_sticker Execution Plan
    # （複数Projectあれば全件）をバッチ生成する。
    #   python services/asset_generator_service.py
    result = generate_assets()
    print(f"[Asset Generator] {result}")
    print()
    print(generate_asset_generator_summary())
