"""
DAF OS Quest90 — Asset Generator v1 サービス

Execution Planner（Quest88）とAsset Type Registry（Quest89）で「何を」「どう」
作るかは計画できるようになったが、実際の成果物（Digital Asset）はまだ何も
生成していなかった。このサービスはExecution Planを起点に、初めて実際の
デジタル資産（LINEスタンプ素材一式）を生成する。

v1では対象を line_sticker のみに限定する。

ゴール：
  Execution Plan → LINEスタンプ素材一式 → CEOレビュー待ち

v1の実装方針（あえてシンプルにする）：
- 画像生成APIはまだ使わない。Pillowで仮画像（プレースホルダー）を生成する。
  理由：(1) まずパイプライン完成を優先する (2) 画像生成API依存・コスト・
  失敗要因を避ける (3) LINEスタンプ制作工程の自動化そのものを検証するため。
  画像品質の改善はv2以降の課題（prompts.mdに将来の画像生成API用プロンプトを
  保存しておき、v2でそのまま利用できるようにしている）。

生成する成果物（outputs/generated_assets/line_sticker/）：
  metadata.md / phrases.md / prompts.md /
  stamp_01.png 〜 stamp_40.png（370×320px, 透明背景）/
  main.png（240×240px）/ tab.png（96×74px）/ stickers.zip

Quest91（Artifact Review Center）で、metadata.mdにGenerated By（制作担当AI社員）・
Reviewer・Reviewed At・Review Decision・Review Reason・Published Atの各項目を
追加した。これらはservices/artifact_review_service.pyがCEOレビューの結果を
書き戻すための項目で、生成直後はReviewer以降すべて「（未定）」になる。

必要な関数：
- generate_assets():                 Execution Plan（line_sticker）を起点に
                                      素材一式を生成し、結果を表すdictを返す
- generate_asset_generator_summary(): AI会議へ注入する短いMarkdown要約を返す

CLI:
  python services/asset_generator_service.py

重複生成防止：outputs/generated_assets/line_sticker/metadata.md が既に存在し、
Statusが pending_review または approved の場合は再生成しない。

Pillow未インストール・Execution Plan未生成・画像生成失敗のいずれでも例外を
投げず、DAF OS全体を止めない。
"""

import re
import sys
import zipfile
from datetime import datetime
from pathlib import Path

# `python services/asset_generator_service.py` のように直接実行された場合、
# リポジトリルートが sys.path に無く `services.*` を解決できないため追加する
# （services/execution_planner_service.py と同じ対策）。
_REPO_ROOT = str(Path(__file__).parent.parent)
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

_BASE_DIR = Path(__file__).parent.parent
_OUTPUTS_DIR = _BASE_DIR / "outputs"
_ASSET_TYPE = "line_sticker"
_GENERATED_ASSETS_DIR_NAME = "generated_assets"

_STAMP_COUNT = 40
_STAMP_SIZE = (370, 320)
_MAIN_SIZE = (240, 240)
_TAB_SIZE = (96, 74)

_DONE_STATUSES = frozenset({"pending_review", "approved"})

_NO_DATA_SUMMARY = "## Asset Generator Summary\n\n現在、生成されたAssetはありません。"

_UNSET = "（未定）"

# Asset Typeごとの制作担当AI社員（Quest91・v1固定）。
# docs/organization.md のDigital Asset Crewに対応する。
_GENERATED_BY = {
    "line_sticker": ["Lyra", "Vega", "Pulsar"],
}

# 日本語（かな漢字）を描画できるフォント候補。上から順に試し、
# 使えるものが無ければPillowのデフォルトフォントにフォールバックする。
_FONT_CANDIDATES = [
    "/System/Library/Fonts/AquaKana.ttc",
    "/System/Library/Fonts/Hiragino Sans GB.ttc",
    "/System/Library/Fonts/Supplemental/Arial Unicode.ttf",
]

# LINEスタンプ用の40フレーズ（v1固定・決定的）。
_PHRASES = [
    "おはよう", "ありがとう", "おつかれさま", "了解です", "こんにちは",
    "おやすみ", "がんばれ", "うれしい", "たのしい", "だいすき",
    "OK!", "またね", "元気だよ", "散歩いこう", "ごはんまだ？",
    "待ってるよ", "お腹すいた", "眠いよ", "嬉しいな", "ごめんね",
    "大丈夫？", "よろしくね", "すごいね", "さすが！", "わかった",
    "おめでとう", "気をつけてね", "応援してるよ", "楽しみ！", "いってきます",
    "ただいま", "おかえり", "頑張ろう", "無理しないで", "ゆっくりしてね",
    "また明日", "なるほど", "まかせて", "だいじょうぶ", "よし！",
]

# Quest94 v2：スタンプごとのバリエーション（画像生成APIは使わず、Pillowのみで
# 表情・文字レイアウト・装飾を組み合わせて視覚的な差を出す）。
_EXPRESSIONS = ["normal", "smile", "sleepy", "surprised", "worried", "cheer", "sorry", "joy"]
_LAYOUTS = ["bottom_center", "top_center", "speech_bubble", "diagonal", "large_text", "two_line"]
_DECORATIONS = ["heart", "star", "note", "teardrop", "sparkle", "bg_circle", "pawprint"]


def _output_dir(outputs_dir: Path) -> Path:
    return outputs_dir / _GENERATED_ASSETS_DIR_NAME / _ASSET_TYPE


def _extract_metadata_status(text: str) -> str | None:
    m = re.search(r"^Status:\s*\n(.+)$", text, re.MULTILINE)
    return m.group(1).strip() if m else None


def _load_font(size: int):
    from PIL import ImageFont
    for path in _FONT_CANDIDATES:
        try:
            if Path(path).exists():
                return ImageFont.truetype(path, size)
        except Exception:
            continue
    return ImageFont.load_default()


def _draw_character(draw, cx: float, cy: float, radius: float, expression: str = "normal") -> None:
    """
    犬っぽいキャラクター（耳付きの丸い頭）を描画する。
    Quest94 v2：expression（表情パターン）に応じて目・口を_draw_face()へ委譲する。
    """
    body_fill = (255, 224, 178, 255)
    outline = (120, 90, 60, 255)

    # 耳（先に描いて、頭で上から重ねる）
    ear_r = radius * 0.42
    draw.ellipse(
        [cx - radius - ear_r * 0.3, cy - radius - ear_r * 0.5,
         cx - radius + ear_r * 1.3, cy - radius + ear_r * 0.9],
        fill=body_fill, outline=outline, width=3,
    )
    draw.ellipse(
        [cx + radius - ear_r * 1.3, cy - radius - ear_r * 0.5,
         cx + radius + ear_r * 0.3, cy - radius + ear_r * 0.9],
        fill=body_fill, outline=outline, width=3,
    )

    # 頭（本体）
    draw.ellipse([cx - radius, cy - radius, cx + radius, cy + radius],
                 fill=body_fill, outline=outline, width=4)

    _draw_face(draw, cx, cy, radius, expression)


def _draw_face(draw, cx: float, cy: float, radius: float, expression: str) -> None:
    """
    Quest94 v2：表情パターン（_EXPRESSIONS）ごとに目・口の描き方を変える。
    未知のexpressionが渡された場合はnormalにフォールバックする。
    """
    dark = (60, 40, 30, 255)
    outline = (120, 90, 60, 255)
    eye_r = max(radius * 0.08, 4)
    eye_dx = radius * 0.42
    eye_dy = radius * 0.15
    lx, ly = cx - eye_dx, cy - eye_dy
    rx, ry = cx + eye_dx, cy - eye_dy
    mouth_cx, mouth_cy = cx, cy + radius * 0.1
    mouth_r = radius * 0.35
    lw = max(int(radius * 0.05), 2)

    if expression == "sleepy":
        for ex in (lx, rx):
            draw.line([ex - eye_r * 1.4, ly, ex + eye_r * 1.4, ly], fill=dark, width=lw)
        draw.arc([mouth_cx - mouth_r * 0.5, mouth_cy, mouth_cx + mouth_r * 0.5, mouth_cy + mouth_r * 0.5],
                  start=20, end=160, fill=outline, width=lw)
    elif expression == "surprised":
        big_r = eye_r * 1.6
        draw.ellipse([lx - big_r, ly - big_r, lx + big_r, ly + big_r], fill=dark)
        draw.ellipse([rx - big_r, ly - big_r, rx + big_r, ly + big_r], fill=dark)
        o_r = mouth_r * 0.35
        draw.ellipse(
            [mouth_cx - o_r, mouth_cy - o_r + mouth_r * 0.2, mouth_cx + o_r, mouth_cy + o_r + mouth_r * 0.2],
            outline=outline, width=lw,
        )
    elif expression == "smile":
        for ex in (lx, rx):
            draw.arc([ex - eye_r * 1.3, ly - eye_r, ex + eye_r * 1.3, ly + eye_r * 1.3],
                      start=200, end=340, fill=dark, width=lw)
        draw.arc([mouth_cx - mouth_r, mouth_cy, mouth_cx + mouth_r, mouth_cy + mouth_r],
                  start=10, end=170, fill=outline, width=lw + 1)
    elif expression == "worried":
        for ex, sign in ((lx, -1), (rx, 1)):
            draw.ellipse([ex - eye_r, ly - eye_r, ex + eye_r, ly + eye_r], fill=dark)
            draw.line([ex - eye_r * 1.5, ly - eye_r * 2.2, ex + sign * eye_r * 0.5, ly - eye_r * 3.2],
                       fill=outline, width=lw)
        draw.line([mouth_cx - mouth_r * 0.4, mouth_cy + mouth_r * 0.3,
                    mouth_cx + mouth_r * 0.4, mouth_cy + mouth_r * 0.1], fill=outline, width=lw)
    elif expression == "cheer":
        for ex in (lx, rx):
            draw.arc([ex - eye_r * 1.3, ly - eye_r, ex + eye_r * 1.3, ly + eye_r * 1.3],
                      start=200, end=340, fill=dark, width=lw)
        draw.pieslice([mouth_cx - mouth_r * 0.8, mouth_cy, mouth_cx + mouth_r * 0.8, mouth_cy + mouth_r],
                       start=10, end=170, fill=(180, 60, 60, 255))
    elif expression == "sorry":
        for ex in (lx, rx):
            draw.line([ex - eye_r, ly - eye_r, ex + eye_r, ly + eye_r], fill=dark, width=lw)
            draw.line([ex - eye_r, ly + eye_r, ex + eye_r, ly - eye_r], fill=dark, width=lw)
        draw.line([mouth_cx - mouth_r * 0.4, mouth_cy + mouth_r * 0.2,
                    mouth_cx + mouth_r * 0.4, mouth_cy - mouth_r * 0.05], fill=outline, width=lw)
    elif expression == "joy":
        for ex in (lx, rx):
            draw.arc([ex - eye_r * 1.4, ly - eye_r * 1.4, ex + eye_r * 1.4, ly + eye_r * 0.6],
                      start=190, end=350, fill=dark, width=lw + 1)
        draw.arc([mouth_cx - mouth_r * 1.1, mouth_cy - mouth_r * 0.1, mouth_cx + mouth_r * 1.1, mouth_cy + mouth_r * 1.1],
                  start=10, end=170, fill=outline, width=lw + 1)
    else:  # normal（未知のexpressionもここへフォールバック）
        draw.ellipse([lx - eye_r, ly - eye_r, lx + eye_r, ly + eye_r], fill=dark)
        draw.ellipse([rx - eye_r, ly - eye_r, rx + eye_r, ly + eye_r], fill=dark)
        draw.arc([mouth_cx - mouth_r, mouth_cy, mouth_cx + mouth_r, mouth_cy + mouth_r],
                  start=20, end=160, fill=outline, width=lw)


# ──────────────────────────────────────────
# Quest94 v2：装飾（_DECORATIONS）
# ──────────────────────────────────────────

_DECORATION_COLORS = {
    "heart": (230, 70, 90, 255),
    "star": (250, 200, 60, 255),
    "note": (90, 90, 200, 255),
    "teardrop": (100, 170, 230, 255),
    "sparkle": (250, 170, 40, 255),
    "bg_circle": (255, 220, 180, 110),
    "pawprint": (150, 110, 80, 255),
}


def _draw_star(draw, cx: float, cy: float, r: float, fill) -> None:
    import math
    points = []
    for i in range(10):
        angle = math.pi / 5 * i - math.pi / 2
        rad = r if i % 2 == 0 else r * 0.45
        points.append((cx + rad * math.cos(angle), cy + rad * math.sin(angle)))
    draw.polygon(points, fill=fill)


def _draw_heart(draw, cx: float, cy: float, r: float, fill) -> None:
    draw.ellipse([cx - r, cy - r * 0.6, cx, cy + r * 0.4], fill=fill)
    draw.ellipse([cx, cy - r * 0.6, cx + r, cy + r * 0.4], fill=fill)
    draw.polygon([(cx - r, cy), (cx + r, cy), (cx, cy + r * 1.3)], fill=fill)


def _draw_note(draw, cx: float, cy: float, r: float, fill) -> None:
    draw.ellipse([cx - r * 0.5, cy, cx + r * 0.5, cy + r], fill=fill)
    draw.line([cx + r * 0.45, cy + r * 0.5, cx + r * 0.45, cy - r * 1.2], fill=fill, width=max(int(r * 0.18), 2))
    draw.line([cx + r * 0.45, cy - r * 1.2, cx + r * 0.9, cy - r], fill=fill, width=max(int(r * 0.18), 2))


def _draw_teardrop(draw, cx: float, cy: float, r: float, fill) -> None:
    draw.ellipse([cx - r * 0.6, cy, cx + r * 0.6, cy + r * 1.2], fill=fill)
    draw.polygon([(cx - r * 0.6, cy + r * 0.4), (cx + r * 0.6, cy + r * 0.4), (cx, cy - r)], fill=fill)


def _draw_sparkle(draw, cx: float, cy: float, r: float, fill) -> None:
    draw.line([cx - r, cy, cx + r, cy], fill=fill, width=max(int(r * 0.25), 2))
    draw.line([cx, cy - r, cx, cy + r], fill=fill, width=max(int(r * 0.25), 2))
    draw.line([cx - r * 0.7, cy - r * 0.7, cx + r * 0.7, cy + r * 0.7], fill=fill, width=max(int(r * 0.15), 1))
    draw.line([cx - r * 0.7, cy + r * 0.7, cx + r * 0.7, cy - r * 0.7], fill=fill, width=max(int(r * 0.15), 1))


def _draw_pawprint(draw, cx: float, cy: float, r: float, fill) -> None:
    draw.ellipse([cx - r * 0.5, cy - r * 0.3, cx + r * 0.5, cy + r * 0.7], fill=fill)
    for dx, dy in ((-0.5, -0.7), (-0.15, -0.95), (0.2, -0.95), (0.55, -0.7)):
        pr = r * 0.22
        draw.ellipse([cx + dx * r - pr, cy + dy * r - pr, cx + dx * r + pr, cy + dy * r + pr], fill=fill)


def _draw_bg_circle(draw, w: int, h: int) -> None:
    """装飾"bg_circle"（背景丸）。キャラクターを描く前に呼ぶ。"""
    color = _DECORATION_COLORS["bg_circle"]
    r = min(w, h) * 0.46
    draw.ellipse([w / 2 - r, h * 0.42 - r, w / 2 + r, h * 0.42 + r], fill=color)


def _draw_decorations(draw, w: int, h: int, decoration: str) -> None:
    """
    Quest94 v2：スタンプ左上・右上に小さな装飾アイコンを描画する
    （bg_circleはキャラクター描画前に_draw_bg_circle()で別途処理済みのため、ここでは何もしない）。
    """
    if decoration == "bg_circle" or decoration not in _DECORATION_COLORS:
        return
    color = _DECORATION_COLORS[decoration]
    r = min(w, h) * 0.07
    positions = [(w * 0.14, h * 0.16), (w * 0.86, h * 0.16)]
    for px, py in positions:
        if decoration == "heart":
            _draw_heart(draw, px, py, r, color)
        elif decoration == "star":
            _draw_star(draw, px, py, r, color)
        elif decoration == "note":
            _draw_note(draw, px, py, r, color)
        elif decoration == "teardrop":
            _draw_teardrop(draw, px, py, r, color)
        elif decoration == "sparkle":
            _draw_sparkle(draw, px, py, r, color)
        elif decoration == "pawprint":
            _draw_pawprint(draw, px, py, r, color)


# ──────────────────────────────────────────
# Quest94 v2：文字レイアウト（_LAYOUTS）
# ──────────────────────────────────────────

def _wrap_phrase(phrase: str, max_chars: int = 6) -> list[str]:
    """
    長いフレーズを自動で2行に折り返す。日本語はスペース区切りが無いため、
    文字数がmax_charsを超える場合は中央付近で2分割する。
    """
    if len(phrase) <= max_chars:
        return [phrase]
    mid = (len(phrase) + 1) // 2
    return [phrase[:mid], phrase[mid:]]


def _measure_lines(draw, lines: list[str], font) -> list[tuple]:
    sizes = []
    for line in lines:
        bbox = draw.textbbox((0, 0), line, font=font)
        sizes.append((line, bbox[2] - bbox[0], bbox[3] - bbox[1], bbox))
    return sizes


def _draw_lines(draw, sizes: list[tuple], font, cx: float, start_y: float) -> None:
    """中央揃えで複数行のフレーズを白フチ＋濃い茶色で描画する（既存のスタンプ文字スタイルを踏襲）。"""
    y = start_y
    for line, tw, th, bbox in sizes:
        x = cx - tw / 2 - bbox[0]
        ty = y - bbox[1]
        for dx, dy in ((-2, 0), (2, 0), (0, -2), (0, 2)):
            draw.text((x + dx, ty + dy), line, font=font, fill=(255, 255, 255, 255))
        draw.text((x, ty), line, font=font, fill=(50, 35, 25, 255))
        y += th + 6


def _draw_speech_bubble(draw, sizes: list[tuple], font, w: int, h: int) -> None:
    """layout="speech_bubble"：頭上に吹き出し風の枠を描き、その中にフレーズを入れる。"""
    max_tw = max(tw for _, tw, _, _ in sizes)
    total_th = sum(th for _, _, th, _ in sizes) + (len(sizes) - 1) * 6
    pad_x, pad_y = 14, 10
    bubble_w = max_tw + pad_x * 2
    bubble_h = total_th + pad_y * 2
    bx0 = w / 2 - bubble_w / 2
    by0 = h * 0.05
    bx1 = bx0 + bubble_w
    by1 = by0 + bubble_h

    draw.rounded_rectangle([bx0, by0, bx1, by1], radius=12,
                            fill=(255, 255, 255, 235), outline=(120, 90, 60, 255), width=3)
    draw.polygon(
        [(w / 2 - 8, by1 - 2), (w / 2 + 8, by1 - 2), (w / 2, by1 + 14)],
        fill=(255, 255, 255, 235), outline=(120, 90, 60, 255),
    )
    _draw_lines(draw, sizes, font, w / 2, by0 + pad_y)


def _draw_diagonal_text(img, sizes: list[tuple], font, w: int, h: int) -> None:
    """layout="diagonal"：フレーズを別レイヤーに描いてから回転させ、スタンプへ貼り付ける。"""
    from PIL import Image as PILImage, ImageDraw as PILImageDraw

    text = "\n".join(line for line, _, _, _ in sizes)
    probe = PILImageDraw.Draw(PILImage.new("RGBA", (10, 10)))
    bbox = probe.multiline_textbbox((0, 0), text, font=font, align="center", spacing=6)
    tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]

    pad = 12
    layer = PILImage.new("RGBA", (tw + pad * 2, th + pad * 2), (0, 0, 0, 0))
    layer_draw = PILImageDraw.Draw(layer)
    x = pad - bbox[0]
    y = pad - bbox[1]
    for dx, dy in ((-2, 0), (2, 0), (0, -2), (0, 2)):
        layer_draw.multiline_text((x + dx, y + dy), text, font=font, fill=(255, 255, 255, 255), align="center", spacing=6)
    layer_draw.multiline_text((x, y), text, font=font, fill=(50, 35, 25, 255), align="center", spacing=6)

    rotated = layer.rotate(-14, expand=True, resample=PILImage.BICUBIC)
    px = int(w / 2 - rotated.width / 2)
    py = int(h - rotated.height - 18)
    img.paste(rotated, (px, py), rotated)


def _render_stamp(phrase: str, index: int) -> "Image.Image":
    """
    Quest94 v2：40枚が同じ画像の使い回しに見えないよう、indexから決定的に
    表情（_EXPRESSIONS）・文字レイアウト（_LAYOUTS）・装飾（_DECORATIONS）を
    選び、組み合わせて1枚のスタンプを描画する。周期が異なる（8・6・7）ため、
    40枚の範囲では同じ組み合わせがほぼ重複しない。
    """
    from PIL import Image, ImageDraw

    expression = _EXPRESSIONS[index % len(_EXPRESSIONS)]
    layout = _LAYOUTS[index % len(_LAYOUTS)]
    decoration = _DECORATIONS[index % len(_DECORATIONS)]

    img = Image.new("RGBA", _STAMP_SIZE, (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    w, h = _STAMP_SIZE
    cx, cy, r = w / 2, h * 0.42, min(w, h) * 0.32

    if decoration == "bg_circle":
        _draw_bg_circle(draw, w, h)

    _draw_character(draw, cx, cy, r, expression=expression)
    _draw_decorations(draw, w, h, decoration)

    if layout == "large_text":
        font = _load_font(38)
        lines = _wrap_phrase(phrase, max_chars=8)
    elif layout == "two_line":
        font = _load_font(26)
        lines = _wrap_phrase(phrase, max_chars=3)
    else:
        font = _load_font(28)
        lines = _wrap_phrase(phrase, max_chars=6)

    sizes = _measure_lines(draw, lines, font)

    if layout == "speech_bubble":
        _draw_speech_bubble(draw, sizes, font, w, h)
    elif layout == "diagonal":
        _draw_diagonal_text(img, sizes, font, w, h)
    elif layout == "top_center":
        _draw_lines(draw, sizes, font, w / 2, h * 0.06)
    else:  # bottom_center / large_text / two_line
        total_h = sum(th for _, _, th, _ in sizes) + (len(sizes) - 1) * 6
        _draw_lines(draw, sizes, font, w / 2, h - total_h - 24)

    return img


def _render_icon(size: tuple[int, int]) -> "Image.Image":
    from PIL import Image, ImageDraw

    img = Image.new("RGBA", size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    w, h = size
    cx, cy = w / 2, h / 2
    r = min(w, h) * 0.38
    _draw_character(draw, cx, cy, r)
    return img


def _safe_line_sticker_plans(outputs_dir: Path) -> list[dict]:
    try:
        from services.execution_planner_service import list_execution_plans
        return list_execution_plans(asset_type=_ASSET_TYPE, outputs_dir=outputs_dir)
    except Exception as e:
        print(f"[警告] Execution Planの取得に失敗しました：{e}")
        return []


def generate_assets(outputs_dir: Path | None = None) -> dict:
    """
    outputs/execution_plans/ に line_sticker のExecution Planが存在する場合、
    outputs/generated_assets/line_sticker/ にLINEスタンプ素材一式
    （phrases.md / prompts.md / stamp_01.png〜stamp_40.png / main.png /
    tab.png / metadata.md / stickers.zip）を生成する。

    重複生成防止：既に metadata.md が存在し、Statusが pending_review または
    approved の場合は再生成しない。

    戻り値: {"status": "generated" | "skipped_existing" | "no_plan" | "error",
             "asset_type": "line_sticker", ...}
    Execution Planが無い・Pillow未インストール・画像生成失敗のいずれでも
    例外を投げず、DAF OS全体を止めない。
    """
    base_outputs_dir = outputs_dir or _OUTPUTS_DIR
    target_dir = _output_dir(base_outputs_dir)
    metadata_path = target_dir / "metadata.md"

    plans = _safe_line_sticker_plans(base_outputs_dir)
    if not plans:
        return {"status": "no_plan", "asset_type": _ASSET_TYPE}

    if metadata_path.exists():
        try:
            existing_status = _extract_metadata_status(metadata_path.read_text(encoding="utf-8"))
        except Exception:
            existing_status = None
        if existing_status in _DONE_STATUSES:
            return {
                "status": "skipped_existing",
                "asset_type": _ASSET_TYPE,
                "existing_status": existing_status,
                "output_dir": str(target_dir),
            }

    try:
        target_dir.mkdir(parents=True, exist_ok=True)

        project = plans[0].get("project") or "LINEスタンプ"
        generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")

        # phrases.md
        phrases_lines = [f"{i}. {p}" for i, p in enumerate(_PHRASES, start=1)]
        (target_dir / "phrases.md").write_text("\n".join(phrases_lines) + "\n", encoding="utf-8")

        # prompts.md（将来の画像生成API用）
        prompt_blocks = [
            f"stamp_{i:02d}:\n"
            f"A cute shiba inu LINE sticker saying \"{phrase}\", "
            "simple flat illustration, transparent background"
            for i, phrase in enumerate(_PHRASES, start=1)
        ]
        (target_dir / "prompts.md").write_text("\n\n".join(prompt_blocks) + "\n", encoding="utf-8")

        # スタンプ画像（仮画像・Pillow生成。Quest94 v2：表情・レイアウト・装飾のバリエーション付き）
        stamp_filenames = []
        for i, phrase in enumerate(_PHRASES, start=1):
            filename = f"stamp_{i:02d}.png"
            img = _render_stamp(phrase, i - 1)
            img.save(target_dir / filename)
            stamp_filenames.append(filename)

        # main.png / tab.png
        _render_icon(_MAIN_SIZE).save(target_dir / "main.png")
        _render_icon(_TAB_SIZE).save(target_dir / "tab.png")

        # metadata.md
        file_list = stamp_filenames + ["main.png", "tab.png", "stickers.zip"]
        generated_by = _GENERATED_BY.get(_ASSET_TYPE, [])
        metadata_lines = [
            "# LINE Sticker Metadata",
            "",
            "Project:",
            project,
            "",
            "Asset Type:",
            _ASSET_TYPE,
            "",
            "Generated At:",
            generated_at,
            "",
            "Status:",
            "pending_review",
            "",
            "Generated By:",
        ]
        metadata_lines.extend(f"- {name}" for name in generated_by)
        metadata_lines.extend([
            "",
            "Reviewer:",
            _UNSET,
            "",
            "Reviewed At:",
            _UNSET,
            "",
            "Review Decision:",
            _UNSET,
            "",
            "Review Reason:",
            _UNSET,
            "",
            "Published At:",
            _UNSET,
            "",
            "## Files",
        ])
        metadata_lines.extend(f"- {f}" for f in file_list)
        metadata_lines.extend([
            "",
            "## Notes",
            "v1では仮画像をPythonで生成。",
            "画像生成AI連携は今後のQuestで追加。",
        ])
        metadata_path.write_text("\n".join(metadata_lines) + "\n", encoding="utf-8")

        # stickers.zip（生成したPNGとmetadataをZIP化）
        zip_path = target_dir / "stickers.zip"
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            for filename in stamp_filenames + ["main.png", "tab.png"]:
                zf.write(target_dir / filename, arcname=filename)
            zf.write(metadata_path, arcname="metadata.md")

        # Notification Center（Quest92）へ通知する。失敗しても生成自体は成功として扱う。
        try:
            from services.notification_service import add_notification
            add_notification(
                "Asset Generated",
                "LINEスタンプ素材一式が生成されました。レビューしてください。",
                level="success",
                source="asset_generator",
                outputs_dir=base_outputs_dir,
            )
        except Exception as e:
            print(f"[警告] Notification Centerへの通知に失敗しました：{e}")

        return {
            "status": "generated",
            "asset_type": _ASSET_TYPE,
            "project": project,
            "output_dir": str(target_dir),
            "zip_path": str(zip_path),
            "stamp_count": len(stamp_filenames),
        }
    except Exception as e:
        print(f"[警告] Asset Generatorの生成に失敗しました：{e}")
        return {"status": "error", "asset_type": _ASSET_TYPE, "error": str(e)}


def generate_asset_generator_summary(outputs_dir: Path | None = None) -> str:
    """
    outputs/generated_assets/line_sticker/metadata.md を読み込み、AI会議へ
    注入する短いMarkdown要約に整形する（services/memory_service.py の
    load_company_memory() から呼ばれる）。ファイル未存在・読み込み失敗の
    いずれの場合も「現在、生成されたAssetはありません。」を返す。例外を投げない。
    """
    try:
        base = outputs_dir or _OUTPUTS_DIR
        metadata_path = _output_dir(base) / "metadata.md"
        if not metadata_path.exists():
            return _NO_DATA_SUMMARY

        text = metadata_path.read_text(encoding="utf-8")
        status = _extract_metadata_status(text) or "unknown"

        lines = [
            "## Asset Generator Summary",
            "",
            "### Generated Assets",
            "",
            f"- {_ASSET_TYPE}: {status}",
            "",
            "### Output",
            f"outputs/{_GENERATED_ASSETS_DIR_NAME}/{_ASSET_TYPE}/stickers.zip",
            "",
            "### Recommendation",
            "CEOが生成物を確認してください。",
        ]
        return "\n".join(lines).rstrip()
    except Exception as e:
        print(f"[警告] Asset Generator Summaryの生成に失敗しました：{e}")
        return _NO_DATA_SUMMARY


def list_generated_assets(outputs_dir: Path | None = None) -> list[dict]:
    """
    outputs/generated_assets/*/metadata.md を読み込み専用でスキャンし、
    Dashboard（Quest93試験運用版）の「Generated Assets」タブ向けに構造化
    データで返す（Dashboard/CEO Home APIから呼ばれる）。

    戻り値: [{"asset_type": str, "status": str, "files_count": int,
              "generated_at": str | None, "zip_path": str | None}, ...]
    ディレクトリ未存在・読み込み失敗のいずれでも例外を投げず、空リストを返す。
    """
    try:
        base = outputs_dir or _OUTPUTS_DIR
        assets_root = base / _GENERATED_ASSETS_DIR_NAME
        if not assets_root.exists():
            return []

        results = []
        for asset_dir in sorted(assets_root.iterdir()):
            metadata_path = asset_dir / "metadata.md"
            if not asset_dir.is_dir() or not metadata_path.exists():
                continue
            try:
                text = metadata_path.read_text(encoding="utf-8")
            except Exception:
                continue

            generated_at_m = re.search(r"^Generated At:\s*\n(.+)$", text, re.MULTILINE)
            zip_path = asset_dir / "stickers.zip"

            results.append({
                "asset_type": asset_dir.name,
                "status": _extract_metadata_status(text) or "unknown",
                "files_count": len([f for f in asset_dir.iterdir() if f.is_file()]),
                "generated_at": generated_at_m.group(1).strip() if generated_at_m else None,
                "zip_path": f"outputs/{_GENERATED_ASSETS_DIR_NAME}/{asset_dir.name}/stickers.zip" if zip_path.exists() else None,
            })
        return results
    except Exception as e:
        print(f"[警告] Generated Assetsの取得に失敗しました：{e}")
        return []


def get_line_sticker_detail(outputs_dir: Path | None = None) -> dict:
    """
    Quest94 v2：Dashboardの「LINEスタンプ生成結果」セクション向けに、
    outputs/generated_assets/line_sticker/ の内容を構造化データで返す
    （フォルダを開かなくてもmetadata・phrases・スタンプ一覧・zip有無を
    確認できるようにするため）。

    戻り値: {"exists": bool, "output_dir": str, "status": str,
             "metadata_text": str, "phrases_text": str,
             "stamp_files": list[str], "main_exists": bool,
             "tab_exists": bool, "zip_exists": bool}
    未生成・読み込み失敗のいずれでも例外を投げず、{"exists": False}を返す。
    """
    try:
        base = outputs_dir or _OUTPUTS_DIR
        target_dir = _output_dir(base)
        metadata_path = target_dir / "metadata.md"
        if not target_dir.exists() or not metadata_path.exists():
            return {"exists": False}

        try:
            metadata_text = metadata_path.read_text(encoding="utf-8")
        except Exception:
            metadata_text = ""

        phrases_text = ""
        phrases_path = target_dir / "phrases.md"
        if phrases_path.exists():
            try:
                phrases_text = phrases_path.read_text(encoding="utf-8")
            except Exception:
                phrases_text = ""

        stamp_files = sorted(f.name for f in target_dir.glob("stamp_*.png") if f.is_file())

        return {
            "exists": True,
            "output_dir": str(target_dir),
            "status": _extract_metadata_status(metadata_text) or "unknown",
            "metadata_text": metadata_text,
            "phrases_text": phrases_text,
            "stamp_files": stamp_files,
            "main_exists": (target_dir / "main.png").exists(),
            "tab_exists": (target_dir / "tab.png").exists(),
            "zip_exists": (target_dir / "stickers.zip").exists(),
        }
    except Exception as e:
        print(f"[警告] LINE Sticker詳細の取得に失敗しました：{e}")
        return {"exists": False, "error": str(e)}


if __name__ == "__main__":
    # Quest90: Dashboard/main.pyの日次バッチを待たずに手動で再生成したい場合のCLI導線。
    #   python services/asset_generator_service.py
    result = generate_assets()
    print(f"[Asset Generator] {result}")
    print()
    print(generate_asset_generator_summary())
